Added a trap for SIGTERM and SIGINT

diff --git a/darip b/darip
--- a/darip
+++ b/darip
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # TODO
-# 0. Trap Ctrl+C, Ctrl+Z
+#
 # 1. Range of tracks to be ripped (1,2,4,5 | 2-12)
 # 2. Basic tagging (Artist, Album, Year, Genre, Comment)
 # 3. mp3gain
@@ -12,6 +12,9 @@ function exit_on_error {
     echo -e "$1"
     exit 1
 }
+
+trap "exit_on_error '\nCaught SIGTERM/SIGINT'" SIGTERM SIGINT
+#trap "cleanup" ERR
 
 # Check if transcode is installed
 #
